### ISSUE TITLE
pulling from github doesn't appear to respect branches in the URL

### ISSUE THREAD

**Issue by jasonkarns** [michaelfaith/package-json-validator#19]

**Comment by JoshuaKGoldberg** [comment]
Since it's been a decade, nobody's commented on this, and I don't know what this means, I'm going to assume it's since been resolved or re-filed in a separate issue. Someone please yell at me if I'm wrong. Cheers! 🧡

**Comment by jasonkarns** [comment]
The issue was duplicated and now covered by https://github.com/TechNickAI/package.json-validator/issues/41
