### ISSUE TITLE
🚀 Feature: Add support for "repository" warnings in npm 

### ISSUE THREAD

**Issue by gravitystorm** [michaelfaith/package-json-validator#20]
`npm install` will warn the end-user if there's no repository field for a package, so it makes sense to warn the developer too :-)

For example,

```
npm WARN package.json zipfile@0.4.3 No repository field.
npm WARN package.json zipfile@0.4.3 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
```

As a bonus, it would of course be nice to warn about the inclusion of the unsupported `repositories` field at the same time.

**Comment by JoshuaKGoldberg** [comment]
> I think this suppression should be removed.

👋 @gravitystorm, coming back to this an admittedly long time later: do you still think this? If so, could you explain a bit why? If npm allows suppressing `repository` when there is `repositories` field, I don't see why this package should go against that. Maybe I'm misunderstanding?

**Comment by gravitystorm** [comment]
@JoshuaKGoldberg To be honest, a decade later I have no memory of this at all! And more importantly, I have no idea if `npm` behaves differently than it used to. I can no longer install the package version that triggered this situation, so I can't reproduce it either. So feel free to close this down.

To (attempt to) summarise the original situation, with a package file that contained "repositories" but not "repository", this validator used to give no warnings, but `npm` would give warnings, and so this was inconsistent behaviour between the two.

But like I say, 10 years is a long time, and it's not something that I've had to deal with in the meantime!

**Comment by JoshuaKGoldberg** [comment]
Works for me 😄 thanks!
