### ISSUE TITLE
support for license (singular)

### ISSUE THREAD

**Issue by pdehaan** [michaelfaith/package-json-validator#26]
### Steps to reproduce:
1. On http://package-json-validator.com/ enter the URL: https://github.com/isaacs/node-tap
### Actual results:

``` json
{
  "valid": false,
  "errors": [
    "Type for field license, was expected to be string, not object",
    "Type for field repository, was expected to be object, not string"
  ],
  "warnings": [
    "Missing recommended field: bugs"
  ],
  "recommendations": [
    "Missing optional field: homepage"
  ]
}
```
### Expected results:

We should support the singular version of license. I figure @isaacs knows a thing or two about package.json and license is valid. I found https://www.npmjs.org/doc/files/package.json.html#license but it only mentions the shorthand version of the license as a strong, not as an object. And makes no mention of licenses[] plural.

**Comment by JoshuaKGoldberg** [comment]
Looks like `license` (singular) has since been given support, so I'm going to go ahead and close this out as resolved. Cheers! 🧡

As for `repository`, the shorthand string is now deprecated in favor of the full object: https://github.com/npm/cli/issues/7299#issuecomment-2010009355
