### ISSUE TITLE
Support for shorthand GitHub strings for repository field

### ISSUE THREAD

**Issue by pdehaan** [michaelfaith/package-json-validator#29]
I'm getting an error with the following value in my package.json file:

```
"repository": "mozilla/fxa-profile-server",
```

```
package.json is NOT valid
{ valid: false,
  errors: [ 'Type for field repository, was expected to be object, not string' ],
  warnings:
   [ 'Missing recommended field: keywords',
     'Missing recommended field: contributors' ] }
```

I believe this was added in npm 1.3.10 (per http://dailyjs.com/2013/09/06/npm-updates/). In fact, I think this may be the npm issue: https://github.com/npm/npm/issues/3783

**Comment by mistadikay** [comment]
Any update on this? This is actually a valid value according to the npm specs: https://docs.npmjs.com/files/package.json#repository

**Comment by stevenvachon** [comment]
@gorillamania this

**Comment by Kristinita** [comment]
+1

**Comment by JoshuaKGoldberg** [comment]
Per https://github.com/npm/cli/issues/7299#issuecomment-2010009355, shorthand strings are now deprecated in favor of long-form objects. `npm publish` now gives a warning for them. Alas.

Closing this out as no longer something npm encourages. Cheers! 🧡
