### ISSUE TITLE
Use a .travis.yml file to run npm test on each push to repo

### ISSUE THREAD

**Issue by pdehaan** [michaelfaith/package-json-validator#31]
Yay Travis!

I think all you'd need is to create a **.travis.yml** file and add the following contents (as well as sign up at https://travis-ci.org/ and tell it to watch this repo):

``` yaml
language: node_js
node_js:
  - "0.10"
```

This should run `npm install` and `npm test` for you automatically. Then just add a fancy badge to your README.md to see the current status. We may need to tweak another couple things like adding `before_install` which installs the **grunt-cli** or whatever.

**Comment by JoshuaKGoldberg** [comment]
...and thus the tech wheel continues to turn. Travis is now out of vogue. GitHub Actions are in.

I'll file separate issues around overhauling this repo's tooling. Cheers! 🧡

> Ooh, the wheel in the sky keeps on turnin
> I don't know where I'll be tomorrow
> Wheel in the sky keeps on turnin
