### ISSUE TITLE
author attribute isn't a required field for npm

### ISSUE THREAD

**Issue by claycarpenter** [michaelfaith/package-json-validator#42]
It looks like the `author` field is required by package.json-validator, but not by npm. 

I don't see any mention of the author field being required in the published [npm package.json documentation](https://docs.npmjs.com/files/package.json). I only see that the `name` and `version` fields are required:

> The most important things in your package.json are the name and version fields. Those are actually required, and your package won't install without them.

I tested this out against older and more recent versions of npm. I put together a very [minimal module](https://gist.github.com/claycarpenter/15b5e6c8762342a8ce38) that contains ony `name` and `version` attributes, and attempted to declare that minimal module as a dependency of another [empty module](https://gist.github.com/claycarpenter/0c81f039f729de587092). Everything (install, uninstall, update, etc.) seems to work fine even though the minimal module doesn't contain the `author` attribute.

Am I missing something, or is this a bug?

**Comment by halfdan** [comment]
@gorillamania Can you release a new version to reflect this change? The version on npm is outdated.

**Comment by TechNickAI** [comment]
Done. 0.6 is pushed.

**Comment by claycarpenter** [comment]
@gorillamania Thanks!
