### ISSUE TITLE
Invalid version range for =... movie-scheduler: file:./*path*

### ISSUE THREAD

**Issue by everyonesdesign** [michaelfaith/package-json-validator#47]
Local dependencies paths are valid now but not considered as valid by app.
Here's local paths [docs link](https://docs.npmjs.com/files/package.json#local-paths)

**Comment by reggi** [comment]
If this was fixed over a year ago why is this still happening?

**Comment by JoshuaKGoldberg** [comment]
It was fixed in Robbert's fork, not this project itself.

I believe this is a duplicate of #38. Someone please yell at me if it's not 🙂 . Cheers! 🧡
