### ISSUE TITLE
Add check for vulnerable modules (using nsp)

### ISSUE THREAD

**Issue by pdehaan** [michaelfaith/package-json-validator#53]
Re: https://www.npmjs.com/package/nsp

It may be nice to be able to opt-in to security checking using the nsp API, where you post the package.json to nsp and could display any potentially vulnerable modules.

**Comment by JoshuaKGoldberg** [comment]
Welp:

> The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

Now on https://blog.npmjs.org/post/175511531085/insert-title-here.html.

Closing this out as `npm audit` is its own separate built-in command. Cheers! 🧡
