### ISSUE TITLE
Latest version shows as 0.6.1 in npm?

### ISSUE THREAD

**Issue by ErisDS** [michaelfaith/package-json-validator#55]
Hi, just wanted to flag up that the package.json in the repo states the version as 0.6.0, but on npm it says 0.6.1 😁 

There are no tags since 0.5.6 and no changelog so I'm wondering what is in 0.6.1 🤔

Also: Is this module likely to be actively maintained again? I'm using it for a project and need to get some updates in. I can PR but my last issue didn't get a reply so I thought I'd ask before PRing or forking.

**Comment by TechNickAI** [comment]
Hey there! 

Yes - this is a supported / maintained project. I was on vacation. Happy to accept pull requests.

**Comment by TechNickAI** [comment]
It looks like the pull request has a conflict. Let me know when that is resolved.

**Comment by ErisDS** [comment]
The PR Is not for this repo, it is for the project that I am maintaining which depends on this project.

This issue was asking you to make the version number for this project clear and consistent please.

**Comment by ErisDS** [comment]
@gorillamania Did my reply above make sense?

**Comment by TechNickAI** [comment]
Bumped to 0.6.2 everywhere
