### ISSUE TITLE
Malware alert on homepage

### ISSUE THREAD

**Issue by aral** [michaelfaith/package-json-validator#72]
Clicking the homepage link presents the following malware alert from uBlock Origin:

```
uBlock Origin has prevented the following page from loading:

http://click.expmediadirect1.com/click?i=pW1KX8XbnF0_0

Because of the following filter:

||expmediadirect1.com^

Found in: uBlock filters – Badware risks 
```

**Comment by JoshuaKGoldberg** [comment]
Well, looks like the webpage is no longer a malware page. But the page is still not owned by anybody affiliated with this project. Filed #79 for tracking.

Aside: hi @aral! 😄

**Comment by aral** [comment]
Hellos 👋🤓 💕
